In [2]:
print ("Hi")

Hi

In [2]:
from google.cloud import bigquery

In [3]:
import matplotlib.pyplot as plt

In [4]:
import numpy as np
import pandas as pd

In [6]:
client = bigquery.Client(project = 'sn-1992')

In [7]:
from pandas.io import gbq

In [19]:
df = gbq.read_gbq('Select author from Test_Data_03_28.comments_copy', project_id = 'sn-1992')

Requesting query... ok.
Job ID: job_YsG90O0rCmNrsBwkKi9zgJhwDw3D
Query running...
  Elapsed 10.71 s. Waiting...
  Elapsed 21.12 s. Waiting...
Query done.
Processed: 77.4 MB
Standard price: $0.00 USD

Retrieving results...
  Got page: 1; 1% done. Elapsed 23.89 s.
  Got page: 2; 2% done. Elapsed 25.72 s.
  Got page: 3; 4% done. Elapsed 28.22 s.
  Got page: 4; 5% done. Elapsed 30.35 s.
  Got page: 5; 6% done. Elapsed 32.26 s.
  Got page: 6; 7% done. Elapsed 34.33 s.
  Got page: 7; 8% done. Elapsed 36.53 s.
  Got page: 8; 10% done. Elapsed 38.51 s.
  Got page: 9; 11% done. Elapsed 40.61 s.
  Got page: 10; 12% done. Elapsed 42.75 s.
  Got page: 11; 13% done. Elapsed 45.5 s.
  Got page: 12; 14% done. Elapsed 47.82 s.
  Got page: 13; 15% done. Elapsed 50.19 s.
  Got page: 14; 17% done. Elapsed 53.25 s.
  Got page: 15; 18% done. Elapsed 55.31 s.
  Got page: 16; 19% done. Elapsed 57.52 s.
  Got page: 17; 20% done. Elapsed 59.62 s.
  Got page: 18; 21% done. Elapsed 62.28 s.
  Got page: 19; 23% done. Elapsed 64.23 s.
  Got page: 20; 24% done. Elapsed 66.81 s.
  Got page: 21; 25% done. Elapsed 68.94 s.
  Got page: 22; 26% done. Elapsed 71.95 s.
  Got page: 23; 27% done. Elapsed 74.1 s.
  Got page: 24; 29% done. Elapsed 76.39 s.
  Got page: 25; 30% done. Elapsed 78.42 s.
  Got page: 26; 31% done. Elapsed 80.75 s.
  Got page: 27; 32% done. Elapsed 82.79 s.
  Got page: 28; 33% done. Elapsed 85.46 s.
  Got page: 29; 35% done. Elapsed 87.8 s.
  Got page: 30; 36% done. Elapsed 90.04 s.
  Got page: 31; 37% done. Elapsed 92.25 s.
  Got page: 32; 38% done. Elapsed 94.21 s.
  Got page: 33; 39% done. Elapsed 96.21 s.
  Got page: 34; 40% done. Elapsed 98.48 s.
  Got page: 35; 42% done. Elapsed 101.7 s.
  Got page: 36; 43% done. Elapsed 103.81 s.
  Got page: 37; 44% done. Elapsed 105.93 s.
  Got page: 38; 45% done. Elapsed 108.14 s.
  Got page: 39; 46% done. Elapsed 110.84 s.
  Got page: 40; 48% done. Elapsed 112.99 s.
  Got page: 41; 49% done. Elapsed 115.28 s.
  Got page: 42; 50% done. Elapsed 117.28 s.
  Got page: 43; 51% done. Elapsed 119.4 s.
  Got page: 44; 52% done. Elapsed 122.88 s.
  Got page: 45; 54% done. Elapsed 124.82 s.
  Got page: 46; 55% done. Elapsed 126.98 s.
  Got page: 47; 56% done. Elapsed 129.24 s.
  Got page: 48; 57% done. Elapsed 131.57 s.
  Got page: 49; 58% done. Elapsed 133.86 s.
  Got page: 50; 60% done. Elapsed 136.06 s.
  Got page: 51; 61% done. Elapsed 138.32 s.
  Got page: 52; 62% done. Elapsed 140.42 s.
  Got page: 53; 63% done. Elapsed 142.74 s.
  Got page: 54; 64% done. Elapsed 144.94 s.
  Got page: 55; 65% done. Elapsed 148.36 s.
  Got page: 56; 67% done. Elapsed 150.84 s.
  Got page: 57; 68% done. Elapsed 153.18 s.
  Got page: 58; 69% done. Elapsed 155.34 s.
  Got page: 59; 70% done. Elapsed 157.59 s.
  Got page: 60; 71% done. Elapsed 159.85 s.
  Got page: 61; 73% done. Elapsed 162.05 s.
  Got page: 62; 74% done. Elapsed 164.75 s.
  Got page: 63; 75% done. Elapsed 167.19 s.
  Got page: 64; 76% done. Elapsed 169.38 s.
  Got page: 65; 77% done. Elapsed 171.65 s.
  Got page: 66; 79% done. Elapsed 174.07 s.
  Got page: 67; 80% done. Elapsed 176.42 s.
  Got page: 68; 81% done. Elapsed 181.24 s.
  Got page: 69; 82% done. Elapsed 183.46 s.
  Got page: 70; 83% done. Elapsed 186.15 s.
  Got page: 71; 85% done. Elapsed 189.09 s.
  Got page: 72; 86% done. Elapsed 191.39 s.
  Got page: 73; 87% done. Elapsed 194.23 s.
  Got page: 74; 88% done. Elapsed 196.56 s.
  Got page: 75; 89% done. Elapsed 199.06 s.
  Got page: 76; 90% done. Elapsed 201.48 s.
  Got page: 77; 92% done. Elapsed 203.62 s.
  Got page: 78; 93% done. Elapsed 206.78 s.
  Got page: 79; 94% done. Elapsed 211.89 s.
  Got page: 80; 95% done. Elapsed 215.23 s.
  Got page: 81; 96% done. Elapsed 218.29 s.
  Got page: 82; 98% done. Elapsed 220.57 s.
  Got page: 83; 99% done. Elapsed 222.73 s.
  Got page: 84; 100% done. Elapsed 225.59 s.
Got 8399417 rows.

Total time taken 246.57 s.
Finished at 2017-08-10 11:44:14.

In [20]:
df.describe()

         author
count   8171681
unique   236359
top     tptacek
freq      33839

In [21]:
df

             author
0          masklinn
1          masklinn
2          masklinn
3          masklinn
4          masklinn
5          masklinn
6          masklinn
7          masklinn
8          masklinn
9          masklinn
10         masklinn
11         masklinn
12         masklinn
13         masklinn
14         masklinn
15         masklinn
16         masklinn
17         masklinn
18         masklinn
19         masklinn
20         masklinn
21         masklinn
22         masklinn
23         masklinn
24         masklinn
25         masklinn
26         masklinn
27         masklinn
28         masklinn
29         masklinn
...             ...
8399387  tlrobinson
8399388  tnorthcutt
8399389  todayiamme
8399390  tokenadult
8399391  tokenadult
8399392  tokenadult
8399393  tokenadult
8399394  tonyhburns
8399395  touristtam
8399396  triviatise
8399397  tseabrooks
8399398  turbojerry
8399399  turingbook
8399400  tymekpavel
8399401  valisystem
8399402  venomsnake
8399403  venomsnake
8399404  venomsnake
8399405  vtbassmatt
8399406  w1ntermute
8399407  w1ntermute
8399408  w1ntermute
8399409  wall_words
8399410  wallflower
8399411  wallflower
8399412  walterbell
8399413  walterbell
8399414  walterbell
8399415  walterbell
8399416  walterbell

[8399417 rows x 1 columns]